/* Corrections to the Grail source text, applied before parsing.
   The .docx had lost the hyphen in compound words, and each such word was followed
   by a stray line break; a few typing slips are corrected against the printed Grail. */
module.exports = {
  /* compound words whose hyphen was lost; the line break that followed is also removed */
  hyphens: {
    "wideopen": "wide-open",
    "highsounding": "high-sounding",
    "evildoers": "evil-doers",
    "evildoer's": "evil-doer's",
    "tenstringed": "ten-stringed",
    "snakecharmer's": "snake-charmer's",
    "bloodthirsty": "bloodthirsty",
    "openmouthed": "open-mouthed",
    "dryshod": "dry-shod",
    "highridged": "high-ridged",
    "Godseeking": "God-seeking",
    "grayheaded": "gray-headed",
    "everflowing": "ever-flowing",
    "dogflies": "dog-flies",
    "dogfly": "dog-fly",
    "sweetsounding": "sweet-sounding",
    "falsehearted": "false-hearted",
    "midcourse": "mid-course",
    "faroff": "far-off",
    "Openhanded": "Open-handed",
    "dungheap": "dung-heap",
    "halfhearted": "half-hearted",
    "redhot": "red-hot",
    "restingplace": "resting-place",
    "firstborn": "first-born",
    "brokenhearted": "broken-hearted",
    "noonday": "noonday",
    "two-edged": "two-edged",
  },
  /* exact corrections: [as found, as printed] */
  replace: [
    ["I will play on the tenstringed\nHarp", "I will play on the ten-stringed harp"],
    ["nor sits in the company of scorners,and", "nor sits in the company of scorners,"],
    ["ponder on your bed and be still", "ponder on your bed and be still."],
    ["their throat a wideopen\ngrave,", "their throat a wide-open grave,"],
    ["the tongue that speaks highsounding\nwords,", "the tongue that speaks high-sounding words,"],
    ["the God who saves him .", "the God who saves him."],
    ["Psalm 11(10) In Domine confido", "Psalm 11(10) In Domino confido"],
    ["Psalm 68(67) Exsurgat Deusf", "Psalm 68(67) Exsurgat Deus"],
    ["Psalm 81(80) Exulate Deo", "Psalm 81(80) Exsultate Deo"],
    ["Psalm 87(86) Gundamenta ejus", "Psalm 87(86) Fundamenta ejus"],
    ["Psalm 121(120) Levai oculos", "Psalm 121(120) Levavi oculos"],
    ["Psalm 124(123) Nisi qua Dominus", "Psalm 124(123) Nisi quia Dominus"],
    ["Psalm 133(132) Eccem qyan bonum!", "Psalm 133(132) Ecce quam bonum!"],
    ["Psalm 140(139) Exripe me, Domine", "Psalm 140(139) Eripe me, Domine"],
    ["Psalm 52(51) Quid gloriaris ?", "Psalm 52(51) Quid gloriaris?"],
    ["Psalm 147.2(147)\nLauda, Jerusalem", "Psalm 147.2(147) Lauda, Jerusalem"],
    ["Blessed be Lord for he has heard", "Blessed be the Lord for he has heard"],
    ["their cry against me is: \"Yes!\"\nWe saw you do it!\"", "their cry against me is: \"Yes!\nWe saw you do it!\""],
    ["\"how long before he dies", "\"How long before he dies"],
    ["Why have your forgotten me?", "Why have you forgotten me?"],
    ["raise you up to posses the land", "raise you up to possess the land"],
    ["A little longerand\nthe wicked shall have gone.", "A little longer—and the wicked shall have gone."],
    ["The warriors arrows sharpened", "The warrior's arrows sharpened"],
    ["For no man buy his own ransom,", "For no man can buy his own ransom,"],
    ["in God, who word I praise.", "in God, whose word I praise."],
    ["\"Truly\", men shall say,", "\"Truly,\" men shall say,"],
    ["for your have been my help;", "for you have been my help;"],
    ["My offenses truly I know them;\nmy sin is always before me", "My offenses truly I know them;\nmy sin is always before me."],
    ["They laid a snare for my steps\nmy soul was bowed down.", "They laid a snare for my steps,\nmy soul was bowed down."],
    ["Let them ever say: \"The Lord is great\",", "Let them ever say: \"The Lord is great,\""],
    ["are those who ate without cause.", "are those who hate me without cause."],
    ["my pray for your favor.", "my prayer for your favor."],
    ["I looked in vain for compassion, for consoles;", "I looked in vain for compassion, for consolers;"],
    ["Of Israel is own possession.", "of Israel his own possession."],
    ["Remember your people whom who chose long ago,", "Remember your people whom you chose long ago,"],
    ["He turned on them the heat of is anger,", "He turned on them the heat of his anger,"],
    ["You brought a vine our of Egypt;", "You brought a vine out of Egypt;"],
    ["Let there be on foreign god among you.\nno worship of an alien god.", "Let there be no foreign god among you,\nno worship of an alien god."],
    ["His right and hand his holy arm", "His right hand and his holy arm"],
    ["The Lord has made know his salvation;", "The Lord has made known his salvation;"],
    ["He who walk in the way of perfection", "He who walks in the way of perfection"],
    ["before my day are complete,", "before my days are complete,"],
    ["They will are wear out like a garment.", "They will all wear out like a garment."],
    ["to serve man's our needs,", "to serve man's needs,"],
    ["for all shall be her children.\"", "for all shall be her children."],
    ["protect you for he knows my name.", "protect him for he knows my name."],
    ["I shall let you see my saving power.", "I shall let him see my saving power."],
    ["'Do not touch those I have anointed;", "\"Do not touch those I have anointed;"],
    ["They ate up every land in the land;", "They ate up every blade in the land;"],
    ["paid no need to your wonderful deeds.", "paid no heed to your wonderful deeds."],
    ["envious of Moses and\nof Aaron, who was holy to the Lord.", "envious of Moses\nand of Aaron, who was holy to the Lord."],
    ["but pursed the poor and the needy,", "but pursued the poor and the needy,"],
    ["Let them know that is your work,\nThat this is your doing, O Lord.", "Let them know that this is your work,\nthat this is your doing, O Lord."],
    ["who take delight in all his commands.", "who takes delight in all his commands."],
    ["The Lord is at my side; I do not fear.\nwhat can man do against me?", "The Lord is at my side; I do not fear.\nWhat can man do against me?"],
    ["as they all riches were mine.", "as though all riches were mine."],
    ["Then the king sent and released him\nthe ruler of the people set him free,", "Then the king sent and released him,\nthe ruler of the people set him free,"],
    ["When will you console me\n", "When will you console me?\n"],
    ["he will guard you soul.", "he will guard your soul."],
    ["around the your table.", "around your table."],
    ["nor go the bed where I rest.", "nor go to the bed where I rest."],
    ["With that no reaper fill his arms,", "With that no reaper fills his arms,"],
    ["That he will do justice for the needy.", "that he will do justice for the needy."],
    ["that your keep him in mind;", "that you keep him in mind;"],
    ["and raise up all who are bowed down.", "and raises up all who are bowed down."],
    ["protects all who love him ;", "protects all who love him;"],
    ["In mortal men in whom there is no help.", "in mortal men in whom there is no help."],
    ["and a two-edged\nsword in their hand,", "and a two-edged sword in their hand,"],
    ["he scatters hoarfrost\nlike ashes.", "he scatters hoarfrost like ashes."],
    ["He has strengthened the bars of your gates\n", "He has strengthened the bars of your gates,\n"],
  ],
};
