/* The Psalm Tree — branches, twigs, and how verses are gathered onto them.
   Each twig lists:
     re   — a pattern matched against the Grail text of each verse (lower-cased, lines joined)
     add  — verses placed by hand, as "psalm:verse" in Vulgate psalm numbering + Grail verse numbers
     drop — verses the pattern catches but that do not belong
   build-tree.js applies these to data-grail.js and writes data-tree.js. */
module.exports = [
{ id:"nature", name:"Earth, Sky & Water", icon:"🌊", desc:"The elements and the living land",
  twigs:[
  { id:"rivers",  name:"Rivers & streams",        re:/\b(rivers?|streams?|torrents?|brooks?|flowing waters|running (streams|waters)|jordan)\b/ },
  { id:"sea",     name:"The sea & the deep",      re:/\b(seas?|waves|the deep|deeps|depths of the sea|ocean|waters? (rose|roared|saw)|billows|breakers)\b/ },
  { id:"rain",    name:"Rain, dew & snow",        re:/\b(rain|showers?|dew|snow|hailstones|with hail|and hail|fire and hail|frost|hoarfrost|raindrops)\b/ },
  { id:"springs", name:"Springs & fountains",     re:/\b(springs?|fountains?|wells?|pools?|source of life)\b/ },
  { id:"fire",    name:"Fire & flame",            re:/\b(fire|flames?|flaming|burn(s|ing|ed|t)?|blaze[ds]?|blazing|coals?|smoke|furnace|kindled|melts? like wax|wax)\b/ },
  { id:"light",   name:"Light",                   re:/\b(light|lamp|shine[sd]?|shining|radiant|brightness|dawn(s|ing)?)\b/ },
  { id:"dark",    name:"Darkness & shadow",       re:/\b(dark(ness)?|gloom|shadows? of death|deepest darkness|blackness|pitch)\b/ },
  { id:"sun",     name:"Sun, moon & stars",       re:/\b(sun|moon|stars?|sunrise|sunset|rising of the sun|firmament|great lights)\b/ },
  { id:"wind",    name:"Wind & breath",           re:/\b(wind|winds|breath|breathe[sd]?|breeze|gale|blast)\b/ },
  { id:"storm",   name:"Storm, thunder & lightning", re:/\b(storms?|tempest|thunder(s|ed|ing)?|lightning|whirlwind|hurricane)\b/ },
  { id:"clouds",  name:"Clouds & the heavens",    re:/\b(clouds?|skies|sky|the heavens proclaim|stretched out the heavens)\b/ },
  { id:"mount",   name:"Mountains & hills",       re:/\b(mountains?|hills?|mount|peaks?|heights|lebanon|hermon|sinai|tabor|bashan)\b/ },
  { id:"rock",    name:"Rock & stone",            re:/\b(rocks?|stones?|crags?|flint|cliffs?)\b/ },
  { id:"earth",   name:"Earth, dust & clay",      re:/\b(dust|clay|mire|mud|ashes|soil|sand)\b/ },
  { id:"desert",  name:"Desert & dry land",       re:/\b(deserts?|wilderness|trackless wastes?|salty waste|parched|dry (land|ground)|dry, weary land|barren|thirsty (land|ground)|arid)\b/ },
  { id:"trees",   name:"Trees & cedars",          re:/\b(trees?|cedars?|olive|palm tree|forests?|oaks?|willows|poplars|cypress|branches|boughs|sycamore|saplings|leaves)\b/ },
  { id:"vine",    name:"Vine & vineyard",         re:/\b(vines?|vineyard|grapes?)\b/ },
  { id:"grass",   name:"Grass & flowers",         re:/\b(grass|flowers?|flowering|blossom|lilies|hay|fades?|withers?|withered|meadows?|pastures?|green)\b/ },
  { id:"harvest", name:"Seed, harvest & grain",   re:/\b(seed|sow(s|n|ing)?|reap(s|ing)?|harvests?|sheaves|grain|corn|wheat|furrows|threshing|fruit(ful|s)?|yield(s|ed)? (its|their) fruit|crops?)\b/ },
  ]},
{ id:"objects", name:"Things Made by Hands", icon:"🏹", desc:"Weapons, vessels and tools — the archetypes",
  twigs:[
  { id:"bow",     name:"Bow & arrow",             re:/\b(bows|(his|their|my|your|the|a|heavy|enemy's) bow|arrows?|quiver|archers?)\b/ },
  { id:"sword",   name:"Sword & spear",           re:/\b(swords?|spears?|lances?|javelins?|daggers?|blades?|razor)\b/ },
  { id:"shield",  name:"Shield & armor",          re:/\b(shields?|bucklers?|armou?r|helmet|girds?|girded|breastplate)\b/ },
  { id:"stones",  name:"Cornerstone & walls",     re:/\b(corner ?stone|keystone|foundations?|walls?|ramparts?|towers?|bulwark|bricks?|pillars?|beams)\b/ },
  { id:"cup",     name:"Cup, jar & vessel",       re:/\b(cups?|chalice|goblet|bowls?|jars?|potter|vessels?|bottles?|wineskins?|flask|pitchers?)\b/ },
  { id:"lamp",    name:"Lamp",            re:/\b(lamps?|lantern)\b/ },
  { id:"scroll",  name:"Scroll, book & law",      re:/\b(scrolls?|book|written|writing|pen|record|tablets?)\b/ },
  { id:"throne",  name:"Throne, crown & scepter",        re:/\b(thrones?|enthroned|scepters?|sceptres?|rod|footstool|crowns?|crowned|diadem)\b/ },
  { id:"snare",   name:"Snares, nets & traps",    re:/\b(snares?|nets?|traps?|pitfalls?|fowler|noose|ensnared|lie in wait|ambush)\b/ },
  { id:"yoke",    name:"Chains, fetters & yoke",  re:/\b(chains?|fetters?|yokes?|bonds|shackles|irons|prisoners?|captives?|captivity|bound)\b/ },
  { id:"staff",   name:"Staff & crook",           re:/\b(staff|crook|sticks?)\b/ },
  { id:"scales",  name:"Scales & measuring line", re:/\b(scales|balance|measuring line|measure|plumb|weighed?)\b/ },
  { id:"garment", name:"Garments & robes",        re:/\b(garments?|robes?|clothed?|clothing|cloaks?|sackcloth|vestments?|mantle|hem|apparel|dressed|wrapped|cloth(es)?|raiment|gold-woven|linen)\b/ },
  { id:"oil",     name:"Oil & anointing",         re:/\b(oil|anoint(ed|s|ing)?|anointed one|ointment|myrrh|perfume|aloes|cassia|incense|fragrant)\b/ },
  { id:"altar",   name:"Altar & sacrifice",       re:/\b(altars?|sacrifices?|offerings?|holocausts?|victims?|burnt|incense|vows?)\b/ },
  { id:"chariot", name:"Chariots & horses of war",re:/\b(chariots?|horsem[ae]n|cavalry|war-?horse|horse and rider)\b/ },
  { id:"gold",    name:"Gold, silver & treasure", re:/\b(gold(en)?|silver|jewels?|precious stones?|treasures?|riches|wealth|coins?|ransom|purest|refined)\b/ },
  ]},
{ id:"creatures", name:"Creatures", icon:"🕊", desc:"Beasts and birds that carry the soul’s longing",
  twigs:[
  { id:"deer",    name:"Deer & wild goats",             re:/\b(deer|hinds?|stags?|gazelles?|goats find|wild goats?)\b/ },
  { id:"birds",   name:"Sparrow, dove & eagle",   re:/\b(eagles?|sparrows?|swallows|the swallow|doves?|birds?|owls?|pelicans?|storks?|nests?|fledglings?|ravens?|hawk|quails?|fowl|wings?|pinions)\b/ },
  { id:"lion",    name:"Lion",                    re:/\b(lions?|lioness|cubs?|young lions?)\b/ },
  { id:"sheep",   name:"Sheep, lambs & flock",    re:/\b(sheep|lambs?|flocks?|ewes?|rams?|herd|pasture|sheepfolds?|shepherd)\b/ },
  { id:"bulls",   name:"Bulls, oxen & cattle",    re:/\b(bulls?|oxen|ox|calf|calves|cattle|heifers?|buffalo|bullocks?|herds?)\b/ },
  { id:"dogs",    name:"Dogs, jackals & wild beasts", re:/\b(dogs?|jackals?|wolves|boars?|foxes|wild beasts?|beasts of the (field|forest))\b/ },
  { id:"serpent", name:"Serpent & adder",         re:/\b(serpents?|snakes?|adders?|asps?|vipers?|cobra|dragons?|venom|poison)\b/ },
  { id:"leviathan", name:"Sea creatures & Leviathan", re:/\b(leviathan|monsters?|sea creatures?|fish(es)?|whales?|rahab|dragon)\b/ },
  { id:"horse",   name:"Horse & mule",            re:/\b(horses?|mules?|stallion)\b/ },
  { id:"small",   name:"Worm, moth, locust & bee", re:/\b(worms?|moth|locusts?|grasshoppers?|caterpillars?|bees|flies|frogs|gnats|snail|insects?)\b/ },
  ]},
{ id:"places", name:"Places of the Soul", icon:"🏛", desc:"Where the soul is standing right now",
  twigs:[
  { id:"zion",    name:"Zion & Jerusalem",        re:/\b(zion|jerusalem|city of (our )?god|city of the lord|holy city)\b/ },
  { id:"temple",  name:"Temple, house & courts",  re:/\b(temple|sanctuary|courts?|house of the lord|house of god|your house|his house|holy place|dwelling place)\b/ },
  { id:"tent",    name:"Tent & dwelling",         re:/\b(tents?|tabernacle|dwell(s|ing)?|abode)\b/ },
  { id:"gates",   name:"Gates & doors",           re:/\b(gates?|doors?|portals?|threshold|doorkeeper|bars? of|bolts?)\b/ },
  { id:"fortress",name:"Fortress & refuge",       re:/\b(fortress|stronghold|citadels?|refuge|tower of strength|strong tower|shelter|hiding place)\b/ },
  { id:"way",     name:"The path & the way",      re:/\b(paths?|ways?|road|footsteps|walk(s|ed|ing)?|steps|stray(ed)?|wander(ed|ing)?|track)\b/ },
  { id:"pit",     name:"The pit & the grave",     re:/\b(pit|grave|tomb|sheol|abyss|the dead|realm of death|gates of death|depths of the earth|dust of death|underworld|shades)\b/ },
  { id:"exodus",  name:"Egypt & the Exodus",      re:/\b(egypt|pharaoh|red sea|reed sea|the sea divided|moses|aaron|manna|zoan|ham)\b/ },
  { id:"exile",   name:"Exile & strange lands",   re:/\b(exiles?|exile|babylon|foreign land|strange land|alien (soil|people|foes)|stranger|sojourner|meshech|kedar|captivity|pilgrim)\b/ },
  { id:"ends",    name:"The ends of the earth",   re:/\b(ends of the earth|all the earth|whole earth|all the nations|all peoples|from the rising of the sun|coastlands?|islands|every land)\b/ },
  { id:"bed",     name:"Bed & home",              re:/\b(beds?|couch|pillow|home|household|my house|hearth|roof)\b/ },
  { id:"desert",  name:"Wilderness journey",      re:/\b(wilderness|desert|forty years|massah|meribah|trackless)\b/ },
  ]},
{ id:"body", name:"The Body at Prayer", icon:"✋", desc:"The psalms pray with the whole body",
  twigs:[
  { id:"face",    name:"Face",                    re:/\b(faces?|countenance)\b/ },
  { id:"eyes",    name:"Eyes",                    re:/\b(eyes?|eyelids)\b/ },
  { id:"hand",    name:"Hand & right hand",       re:/\b(hands?|right hand|palms?|fingers?|fist)\b/ },
  { id:"arm",     name:"Arm",                     re:/\b(arms?|outstretched)\b/ },
  { id:"heart",   name:"Heart",                   re:/\b(hearts?|hearted|inmost)\b/ },
  { id:"bones",   name:"Bones & flesh",           re:/\b(bones?|flesh|body|frame|marrow|limbs?|skin|sinews?)\b/ },
  { id:"mouth",   name:"Mouth, tongue & lips",    re:/\b(mouths?|tongues?|lips?|throats?|teeth|palate|jaws?)\b/ },
  { id:"ears",    name:"Ears",                    re:/\b(ears?|incline|give ear|turn your ear)\b/ },
  { id:"feet",    name:"Feet & steps",            re:/\b(feet|foot|footsteps|heels?|steps|knees?|ankles?)\b/ },
  { id:"tears",   name:"Tears",                   re:/\b(tears|weep(s|ing)?|wept)\b/ },
  { id:"womb",    name:"Womb & birth",            re:/\b(wombs?|birth|born|breasts?|begotten|conceived|knit me|weaned|infants?|babes?|nursing)\b/ },
  { id:"head",    name:"Head & hair",             re:/\b(heads?|hair|brow|beard|crown of (his|the) head)\b/ },
  { id:"soul",    name:"Soul & spirit",           re:/\b(my soul|my spirit|your spirit|his spirit|a spirit|the spirit)\b/ },
  { id:"blood",   name:"Blood",                   re:/\b(blood|bloodthirsty|bloodshed)\b/ },
  ]},
{ id:"names", name:"Names of God", icon:"✠", desc:"Who do I need God to be today?",
  twigs:[
  { id:"shepherd",name:"Shepherd",                re:/\b(shepherds?|pasture|flock he|sheep of his)\b/ },
  { id:"rock",    name:"Rock",                    re:/\b(my rock|our rock|the rock|a rock|rock of|rock who|rock where)\b/ },
  { id:"refuge",  name:"Refuge & shelter",        re:/\b(refuge|shelter|hiding place|shade|shadow of your wings|under his wings)\b/ },
  { id:"fortress",name:"Fortress & stronghold",   re:/\b(fortress|stronghold|citadel|tower|bulwark)\b/ },
  { id:"shield",  name:"Shield",                  re:/\b(shield|buckler)\b/ },
  { id:"king",    name:"King",                    re:/\b(king|kingship|reigns|is king|enthroned|kingdom)\b/ },
  { id:"judge",   name:"Judge",                   re:/\b(judge[sd]?|judging|judgment|judgments)\b/ },
  { id:"light",   name:"Light & salvation",       re:/\b(my light|light of your face|in your light|lamp to my feet|the lord is my light|sun and shield)\b/ },
  { id:"keeper",  name:"Keeper & guardian",       re:/\b(guards?|guarded|guardian|keeper|watch(es)? over|protects?|protected|protection|keeps? (me|us|israel|all their bones)|keep (me|us|you) (safe|from)|preserves? (me|my|the))\b/ },
  { id:"savior",  name:"Savior & redeemer",       re:/\b(savior|saviour|redeem(er|s|ed)?|ransom(s|ed)?|deliver(er|s|ed)?|rescue[sd]?|saving|salvation|save[sd]? me)\b/ },
  { id:"helper",  name:"Helper",                  re:/\b(help(er)?|come to my aid|my aid|to my assistance|succour)\b/ },
  { id:"father",  name:"Father & mother",         re:/\b(father|mother|as a father|orphans?|fatherless|weaned child)\b/ },
  { id:"maker",   name:"Creator & maker",         re:/\b(made (the )?(heaven|earth|sky|skies|sea|us|me)|maker|creat(ed|or|es)|formed|fashioned|founded the earth|works of your hands|your fingers)\b/ },
  { id:"hosts",   name:"Lord of hosts & Most High", re:/\b(lord of hosts|god of hosts|most high|almighty)\b/ },
  { id:"holy",    name:"The Holy One",            re:/\b(holy one|he is holy|holy is|holiness|holy name)\b/ },
  { id:"portion", name:"My portion & my cup",     re:/\b(portion|inheritance|heritage|my lot|my cup|share)\b/ },
  { id:"warrior", name:"Warrior",                 re:/\b(warrior|mighty in battle|valiant|trains my hands for battle|hero|victory|triumph)\b/ },
  { id:"healer",  name:"Healer",                  re:/\b(heal(s|ed|er)?|healing|binds up|restor(e|es|ed)|revive)\b/ },
  { id:"love",    name:"Faithful love",           re:/\b(love endures|your love|his love|merciful love|steadfast love|faithful love|kindness|compassion|mercy|merciful|faithfulness|faithful)\b/ },
  ]},
{ id:"soul", name:"States of the Soul", icon:"❦", desc:"After Athanasius: a psalm for every movement of the heart",
  twigs:[
  { id:"thirst",  name:"Thirst & longing",        re:/\b(thirsts?|thirsty|thirsting|long for|longs|longed|longing|yearns?|yearning|pines?|pining|faints? for|seek(ing)? your face)\b/ },
  { id:"lovegod", name:"Love for God",            re:/\b(i love (you|the lord|your)|how i love|my love is for|love your (name|saving|law|commands|precepts|will))\b/ },
  { id:"fear",    name:"Fear & dread",            re:/\b(afraid|terror|terrors|dread|trembl(e|ing)|fear(ful)?)\b/ },
  { id:"forsaken",name:"Feeling forsaken",        re:/\b(forsaken?|forsake|forgotten|hide your face|hid(e|den) (his|your) face|cast me off|rejected|why have you|how long|abandon(ed)?|far from me|forgot)\b/ },
  { id:"distress",name:"Distress & anguish",      re:/\b(distress|anguish|troubles?|affliction|afflicted|sorrows?|misery|grief|groan(s|ing)?|overwhelm(ed|s)?|crushed|faint)\b/ },
  { id:"lonely",  name:"Alone & betrayed",        re:/\b(lonely|all alone|one alone|leave me alone|friends?|companions?|betray(ed)?|shunned|stranger to my|lifted his heel)\b/ },
  { id:"guilt",   name:"Guilt & repentance",      re:/\b(sins?|sinned|guilt|iniquity|offenses?|transgressions?|wash me|cleanse|contrite|confess(ed)?|pardon|forgive(n|ness)?|blot out|faults?)\b/ },
  { id:"trust",   name:"Trust & confidence",      re:/\b(trust(s|ed|ing)?|confidence|i shall not fear|not be afraid|will not fear|rely|relies|secure|steadfast|unshaken|safe|safety)\b/ },
  { id:"peace",   name:"Peace & rest",            re:/\b(peace|peaceful|rest(s|ing)?|repose|be still|quiet|calm(s|ed)?|stilled|restful)\b/ },
  { id:"joy",     name:"Joy & gladness",          re:/\b(joy(ful|fully)?|glad(ness)?|rejoic(e|es|ing)|delight(s|ed)?|exult(s|ing)?|happy|merry|jubilant|shout for joy|ring out)\b/ },
  { id:"thanks",  name:"Gratitude & thanksgiving",re:/\b(thank(s|ing)?|thanksgiving|give thanks|grateful|gratitude)\b/ },
  { id:"waiting", name:"Waiting & hope",          not:/\blies? in wait\b/,          re:/\b(wait(s|ed|ing)?|await|hope(s|d)?|hoping|patien(t|ce)|how long)\b/ },
  { id:"anger",   name:"Anger at injustice",      re:/\b(oppress(ed|es|or|ors|ion)?|violence|violent|injustice|unjust(ly)?|bribes?|arrogant|proud men|the proud|scoff(ers?|ing)?|mock(ed|ing|ers|ery)?|taunt(s|ed|ing)?|avenge|vengeance|punish|break (their|the) (teeth|power)|wicked prosper|prosperity of the wicked|repay them|pay them back|how long (will|shall|must|are) the wicked)\b/ },
  { id:"weary",   name:"Weariness & sickness",    re:/\b(weary|wearied|exhausted|worn out|sick(ness)?|ill|feeble|weak(ness)?|wasted|failing|fails|languish(ing)?|spent)\b/ },
  { id:"mortal",  name:"Mortality: life as a breath", re:/\b(breath|mere shadow|passing shadow|evening shadow|days are|few days|shortness of|mortal|fleeting|like grass|we return|our years|seventy years|to dust|the grave)\b/ },
  { id:"awe",     name:"Wonder & awe",            re:/\b(wonders?|wonderful|marvel(s|ous|lous)?|awe(some)?|awesome|glorious|majest(y|ic)|splendou?r|how great|how many are your works)\b/ },
  { id:"humble",  name:"Humility & littleness",   re:/\b(humble|lowly|poor|needy|weaned|not proud|haughty|worm|meek|helpless)\b/ },
  { id:"enemies", name:"Surrounded by enemies",   re:/\b(foes?|enemies|enemy|adversar(y|ies)|attackers?|surround(ed)?|beset|besieged|pursue(rs)?|persecutors?|hunt(ed)?)\b/ },
  { id:"law",     name:"Delight in God’s law",    re:/\b(law|laws|precepts?|statutes?|commands?|commandments?|decrees?|your word|his word|your promise|your will|ordinances?)\b/ },
  ]},
{ id:"gestures", name:"Gestures & Postures", icon:"🙌", desc:"Prayer that moves from the head into the body",
  twigs:[
  { id:"lifthands", name:"Lifting up hands",      re:/\b(lift(ing)? up (my|your) hands|raise[ds]? (my|your) hands|hands (lifted|raised)|stretch(ed)? out my hands|hands to you|lifting of my hands|spread out my hands)\b/ },
  { id:"lifteyes",  name:"Lifting up eyes",       re:/\b(lift up my eyes|eyes are (turned|always|on)|my eyes (are|look|are always)|eyes of servants|to you i lift|to you have i lifted up my eyes|my eyes to)\b/ },
  { id:"bow",       name:"Bowing & kneeling",     re:/\b(bow(s|ed|ing)? (down|low)|kneel|knees|prostrate|fall down|worship|bend the knee|pay him your homage|homage)\b/ },
  { id:"dance",     name:"Dancing & clapping",    re:/\b(danc(e|es|ing)|clap(s|ping)?|leap(s|ed)?|skip(ped)?)\b/ },
  { id:"sleep",     name:"Lying down & sleeping", re:/\b(lie down|sleep(s)?|slept|asleep|slumber(s)?|on my bed|upon my bed|awake|wake)\b/ },
  { id:"watch",     name:"Keeping watch",         re:/\b(watch(es|ing|man|men)?|keep watch|vigil|watchmen|sentinels?|stand(s|ing)? in the house)\b/ },
  { id:"walk",      name:"Walking & going up",    re:/\b(walk(s|ed|ing)?|go up|going up|climb|ascend(s|ed)?|went up|let us go|come before|enter (his|the|your)|go in|process(ion)?|pilgrim)\b/ },
  { id:"still",     name:"Being still",           re:/\b(be still|in silence|silent|still before|quieted|hushed|waits in silence|stilled)\b/ },
  { id:"sackcloth", name:"Fasting & sackcloth",   re:/\b(fasts|fasted|fasting|sackcloth|mourning|ashes|mourn(ed|s)?)\b/ },
  { id:"cry",       name:"Crying out",            re:/\b(cry|cried|cries|call(ed|s)? (to|on|upon) (you|him|the lord)|i call|when i call|call upon)\b/ },
  { id:"bless",     name:"Blessing",              re:/\b(bless(ed|es|ing)?|blessings?)\b/ },
  ]},
{ id:"hours", name:"The Hours", icon:"☀", desc:"Morning, evening and the night watches — the Office in the Psalter",
  twigs:[
  { id:"morning", name:"Dawn & morning",          re:/\b(morning|dawn(s|ing)?|daybreak|wake the dawn|at break of day|early)\b/ },
  { id:"noon",    name:"Noonday",                 re:/\b(noon(day)?|midday|by day|heat of the day|scorch)\b/ },
  { id:"evening", name:"Evening",                 re:/\b(evening|dusk|sunset|going down of the sun|sun sets)\b/ },
  { id:"night",   name:"Night & the night watches", re:/\b(night|nights|night watches|midnight)\b/ },
  { id:"always",  name:"Day & night, all day long", re:/\b(day and night|all day long|all the day|seven times|continually|unceasingly|always|at all times|every day|day after day|day by day|evening, morning and at noon)\b/ },
  { id:"ages",    name:"For ever & from age to age", re:/\b(for ever|forever|age to age|all generations|generation to generation|everlasting|eternal|endless)\b/ },
  ]},
{ id:"food", name:"Food & Drink", icon:"🍞", desc:"The table God prepares",
  twigs:[
  { id:"bread",   name:"Bread & manna",           re:/\b(bread|manna|loaves|food|feed(s|ing)?|fed|eat(s|en|ing)?|ate|meat|flesh like dust)\b/ },
  { id:"wine",    name:"Wine",                    re:/\b(wine|new wine|winepress|vintage|drunk(en|ards)?)\b/ },
  { id:"oil",     name:"Oil",                     re:/\b(oil|olive|fatness|rich (food|fare|banquet)|marrow and fat)\b/ },
  { id:"honey",   name:"Honey & sweetness",       re:/\b(honey|honeycomb|sweet(er|ness)?|taste)\b/ },
  { id:"water",   name:"Water to drink",          re:/\b(drink|drank|water(s)? (from|out of) the rock|quench|water to drink|gave them water)\b/ },
  { id:"table",   name:"Banquet & table",         re:/\b(table|banquet|feast(s|ing)?|abundance|plenty|fill(ed|s)? (the|them|you|us|me)|satisf(y|ied|ies)|filled with good things|good things)\b/ },
  { id:"hunger",  name:"Hunger & fasting",        re:/\b(hunger|hungry|famine|starv(e|ed|ing)|fasts|fasted|fasting|want for nothing)\b/ },
  { id:"tears",   name:"Tears as bread",          re:/\b(tears (have become|are) my (bread|food)|bread of tears|ashes like bread|drink with tears|mingled my drink)\b/ },
  ]},
{ id:"sounds", name:"Sounds & Silence", icon:"🎶", desc:"Harp, trumpet, the shout — and the silence",
  twigs:[
  { id:"harp",    name:"Harp & lyre",             re:/\b(harps?|lyres?|zithers?|ten-stringed|strings)\b/ },
  { id:"trumpet", name:"Trumpet & horn",          re:/\b(trumpets?|horns? (blast|sound)|ram's horn|blast of the trumpet|sound of the horn|shofar)\b/ },
  { id:"timbrel", name:"Timbrel, cymbals & dance",re:/\b(timbrels?|tambourines?|drums?|cymbals?|pipes?|flutes?)\b/ },
  { id:"newsong", name:"The new song",            re:/\b(new song|sing a new)\b/ },
  { id:"singing", name:"Singing & psalms",        re:/\b(sing(s|ing)?|sang|song|songs|psalms?|hymns?|music|melody|chant)\b/ },
  { id:"shout",   name:"The shout of joy",        re:/\b(shout(s|ed|ing)?|cry out with joy|ring out|acclaim|acclamation|jubilant|loud)\b/ },
  { id:"voice",   name:"The voice of the Lord",   re:/\b(voice of the lord|the lord's voice|his voice|he thundered|thunders)\b/ },
  { id:"groan",   name:"Groaning & sighing",      re:/\b(groan(s|ed|ing)?|sigh(s|ed|ing)?|moan(s|ed|ing)?|lament(s|ing)?|wail(ing)?)\b/ },
  { id:"deep",    name:"Deep calling on deep",    re:/\b(deep is calling|roar of (the )?(mighty )?waters|the waters roar|lifted up their (voice|thunder)|surgings? of the sea)\b/ },
  { id:"silence", name:"Silence",                 re:/\b(silen(ce|t|ced)|be still|hushed|speechless|dumb|mute|no speech|no word|stilled|you still)\b/ },
  ]},
{ id:"christ", name:"Christ in the Psalms", icon:"☧", desc:"Verses the New Testament and the Fathers hear on Christ’s lips",
  twigs:[
  { id:"king",    name:"The Son & King",          add:["2:7","2:8","44:7","44:8","71:1","71:10","71:11","88:27","88:28","109:1","109:3","131:11","21:28"] },
  { id:"priest",  name:"The Priest for ever",     add:["109:4","39:7","39:8","39:9"] },
  { id:"incarn",  name:"Son of Man & the Word made flesh", add:["8:5","8:6","8:7","18:5","18:6","84:11","84:12","71:6","2:7"] },
  { id:"teacher", name:"Temptation & teaching",             add:["77:2","8:3","81:6","117:26","90:11","90:12","90:13"] },
  { id:"passion", name:"The Passion",             add:["21:2","21:7","21:8","21:9","21:17","21:18","21:19","40:10","34:11","34:19","68:5","68:10","68:22","30:6","33:21","37:12","87:9","108:8","117:22","2:1","2:2","54:13","54:14","54:15"] },
  { id:"risen",   name:"Resurrection",            add:["15:9","15:10","15:11","3:6","117:17","117:22","117:23","117:24","29:4","29:12","138:18","109:7"] },
  { id:"ascension", name:"Ascension & glory",     add:["23:7","23:8","23:9","23:10","46:6","67:19","109:1","8:6","96:7","101:26","101:27","101:28","103:4","44:7"] },
  { id:"church",  name:"The Church & the nations",add:["116:1","116:2","17:50","21:23","21:26","21:28","86:1","86:2","86:3","86:4","86:5","44:11","44:14","44:15","47:2","47:3","121:3","71:17","95:3"] },
  ]},
];
